export { default as TextSection } from './TextSection'
export { default as FullWidthImage } from './FullWidthImage'
export { default as TwoBlockImageLeft } from './TwoBlockImageLeft'
export { default as TwoBlockImageRight } from './TwoBlockImageRight'
export { default as VideoBanner} from './VideoBanner'
export { default as Feature } from './Feature'
export { default as SliceZone } from './SliceZone'
